[unstable]
json-target-spec = true                         # custom target JSON needs opt-in on recent nightlies
build-std = ["core", "compiler_builtins"]       # add "alloc" at M8
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-kernova.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
